apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp-deployment
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: loginapp-container
          image: rapakakarthik7/dockerrepo:loginapp
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"